// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: api/proto/runtime/v1/driver.proto

package runtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// e.g. "snapshot"
	Instruction string `protobuf:"bytes,1,opt,name=instruction,proto3" json:"instruction,omitempty"`
	// VM/Pod runtime 对象 ID
	SubjectId string `protobuf:"bytes,2,opt,name=subject_id,json=subjectId,proto3" json:"subject_id,omitempty"`
	// arbitrary key-value parameters
	Params map[string]string `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// 幂等 key
	ExecutionId   string `protobuf:"bytes,4,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_api_proto_runtime_v1_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_driver_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetInstruction() string {
	if x != nil {
		return x.Instruction
	}
	return ""
}

func (x *ExecuteRequest) GetSubjectId() string {
	if x != nil {
		return x.SubjectId
	}
	return ""
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type ExecuteReply struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ExitCode   int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	StdoutTail string                 `protobuf:"bytes,2,opt,name=stdout_tail,json=stdoutTail,proto3" json:"stdout_tail,omitempty"`
	StderrTail string                 `protobuf:"bytes,3,opt,name=stderr_tail,json=stderrTail,proto3" json:"stderr_tail,omitempty"`
	// e.g. snapshot path
	Artifacts     map[string]string `protobuf:"bytes,4,rep,name=artifacts,proto3" json:"artifacts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteReply) Reset() {
	*x = ExecuteReply{}
	mi := &file_api_proto_runtime_v1_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteReply) ProtoMessage() {}

func (x *ExecuteReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteReply.ProtoReflect.Descriptor instead.
func (*ExecuteReply) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_driver_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteReply) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *ExecuteReply) GetStdoutTail() string {
	if x != nil {
		return x.StdoutTail
	}
	return ""
}

func (x *ExecuteReply) GetStderrTail() string {
	if x != nil {
		return x.StderrTail
	}
	return ""
}

func (x *ExecuteReply) GetArtifacts() map[string]string {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type Capabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// free-form features supported by this driver
	Features []string `protobuf:"bytes,1,rep,name=features,proto3" json:"features,omitempty"`
	// optional metadata for discovery
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capabilities) Reset() {
	*x = Capabilities{}
	mi := &file_api_proto_runtime_v1_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capabilities) ProtoMessage() {}

func (x *Capabilities) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_runtime_v1_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capabilities.ProtoReflect.Descriptor instead.
func (*Capabilities) Descriptor() ([]byte, []int) {
	return file_api_proto_runtime_v1_driver_proto_rawDescGZIP(), []int{2}
}

func (x *Capabilities) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *Capabilities) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_api_proto_runtime_v1_driver_proto protoreflect.FileDescriptor

const file_api_proto_runtime_v1_driver_proto_rawDesc = "" +
	"\n" +
	"!api/proto/runtime/v1/driver.proto\x12\n" +
	"runtime.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xef\x01\n" +
	"\x0eExecuteRequest\x12 \n" +
	"\vinstruction\x18\x01 \x01(\tR\vinstruction\x12\x1d\n" +
	"\n" +
	"subject_id\x18\x02 \x01(\tR\tsubjectId\x12>\n" +
	"\x06params\x18\x03 \x03(\v2&.runtime.v1.ExecuteRequest.ParamsEntryR\x06params\x12!\n" +
	"\fexecution_id\x18\x04 \x01(\tR\vexecutionId\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf2\x01\n" +
	"\fExecuteReply\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\x12\x1f\n" +
	"\vstdout_tail\x18\x02 \x01(\tR\n" +
	"stdoutTail\x12\x1f\n" +
	"\vstderr_tail\x18\x03 \x01(\tR\n" +
	"stderrTail\x12E\n" +
	"\tartifacts\x18\x04 \x03(\v2'.runtime.v1.ExecuteReply.ArtifactsEntryR\tartifacts\x1a<\n" +
	"\x0eArtifactsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x01\n" +
	"\fCapabilities\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\tR\bfeatures\x12B\n" +
	"\bmetadata\x18\x02 \x03(\v2&.runtime.v1.Capabilities.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x92\x01\n" +
	"\rRuntimeDriver\x12A\n" +
	"\aExecute\x12\x1a.runtime.v1.ExecuteRequest\x1a\x18.runtime.v1.ExecuteReply\"\x00\x12>\n" +
	"\bDiscover\x12\x16.google.protobuf.Empty\x1a\x18.runtime.v1.Capabilities\"\x00B.Z,hackohio/driver/api/gen/runtime/v1;runtimev1b\x06proto3"

var (
	file_api_proto_runtime_v1_driver_proto_rawDescOnce sync.Once
	file_api_proto_runtime_v1_driver_proto_rawDescData []byte
)

func file_api_proto_runtime_v1_driver_proto_rawDescGZIP() []byte {
	file_api_proto_runtime_v1_driver_proto_rawDescOnce.Do(func() {
		file_api_proto_runtime_v1_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_runtime_v1_driver_proto_rawDesc), len(file_api_proto_runtime_v1_driver_proto_rawDesc)))
	})
	return file_api_proto_runtime_v1_driver_proto_rawDescData
}

var file_api_proto_runtime_v1_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_runtime_v1_driver_proto_goTypes = []any{
	(*ExecuteRequest)(nil), // 0: runtime.v1.ExecuteRequest
	(*ExecuteReply)(nil),   // 1: runtime.v1.ExecuteReply
	(*Capabilities)(nil),   // 2: runtime.v1.Capabilities
	nil,                    // 3: runtime.v1.ExecuteRequest.ParamsEntry
	nil,                    // 4: runtime.v1.ExecuteReply.ArtifactsEntry
	nil,                    // 5: runtime.v1.Capabilities.MetadataEntry
	(*emptypb.Empty)(nil),  // 6: google.protobuf.Empty
}
var file_api_proto_runtime_v1_driver_proto_depIdxs = []int32{
	3, // 0: runtime.v1.ExecuteRequest.params:type_name -> runtime.v1.ExecuteRequest.ParamsEntry
	4, // 1: runtime.v1.ExecuteReply.artifacts:type_name -> runtime.v1.ExecuteReply.ArtifactsEntry
	5, // 2: runtime.v1.Capabilities.metadata:type_name -> runtime.v1.Capabilities.MetadataEntry
	0, // 3: runtime.v1.RuntimeDriver.Execute:input_type -> runtime.v1.ExecuteRequest
	6, // 4: runtime.v1.RuntimeDriver.Discover:input_type -> google.protobuf.Empty
	1, // 5: runtime.v1.RuntimeDriver.Execute:output_type -> runtime.v1.ExecuteReply
	2, // 6: runtime.v1.RuntimeDriver.Discover:output_type -> runtime.v1.Capabilities
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_proto_runtime_v1_driver_proto_init() }
func file_api_proto_runtime_v1_driver_proto_init() {
	if File_api_proto_runtime_v1_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_runtime_v1_driver_proto_rawDesc), len(file_api_proto_runtime_v1_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_runtime_v1_driver_proto_goTypes,
		DependencyIndexes: file_api_proto_runtime_v1_driver_proto_depIdxs,
		MessageInfos:      file_api_proto_runtime_v1_driver_proto_msgTypes,
	}.Build()
	File_api_proto_runtime_v1_driver_proto = out.File
	file_api_proto_runtime_v1_driver_proto_goTypes = nil
	file_api_proto_runtime_v1_driver_proto_depIdxs = nil
}
