name: CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Build
        run: go build ./...

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test ./... -race -count=1 -timeout=5m

  integration:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Build driverd
        run: go build -o driverd ./cmd/driverd

      - name: Start driverd (Unix socket)
        run: |
          set -euo pipefail
          ./driverd -socket /tmp/runtime-driver.grpc -features echo,snapshot -verbose &
          echo $! > driverd.pid
          # Wait for socket to appear
          for i in {1..50}; do
            if [ -S /tmp/runtime-driver.grpc ]; then echo "socket ready"; break; fi
            sleep 0.1
          done

      - name: Install grpcurl
        run: |
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: Execute snapshot and verify artifact
        run: |
          set -euo pipefail
          grpcurl -plaintext \
            -d '{"instruction":"snapshot","subject_id":"vm-1","execution_id":"snap-ci"}' \
            unix:///tmp/runtime-driver.grpc runtime.v1.RuntimeDriver/Execute | tee /tmp/execute.json
          grep -q '/var/run/kuberisc/snaps/vm-1.img' /tmp/execute.json

      - name: Stop driverd
        if: always()
        run: |
          if [ -f driverd.pid ]; then kill $(cat driverd.pid) || true; fi

  build-binaries:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goos: windows
            goarch: arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Build driverd for ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
          CGO_ENABLED: 0
        run: |
          set -euo pipefail
          mkdir -p dist
          exe=""; [ "$GOOS" = "windows" ] && exe=".exe"
          bin="driverd${exe}"
          go build -trimpath -ldflags "-s -w" -o "dist/${bin}" ./cmd/driverd
          # Package
          version="${GITHUB_REF_NAME}"
          version=${version//\//-}
          name="driverd_${version}_${GOOS}_${GOARCH}"
          if [ "$GOOS" = "windows" ]; then
            (cd dist && zip -q "${name}.zip" "${bin}")
            sha256sum "dist/${name}.zip" > "dist/${name}.zip.sha256"
          else
            tar -C dist -czf "dist/${name}.tar.gz" "${bin}"
            sha256sum "dist/${name}.tar.gz" > "dist/${name}.tar.gz.sha256"
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: driverd-${{ matrix.goos }}-${{ matrix.goarch }}
          path: |
            dist/*.tar.gz
            dist/*.tar.gz.sha256
            dist/*.zip
            dist/*.zip.sha256

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    needs: [build-test, build-binaries]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Verify build and tests
        run: |
          go build ./...
          go test ./... -count=1

      - name: Go module metadata
        run: |
          echo "Module: $(go list -m)"
          echo "Version: ${GITHUB_REF_NAME}"

      - name: Download built binaries
        uses: actions/download-artifact@v4
        with:
          path: release

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            release/**
